services:
  api:
    container_name: api
    restart: always
    image: node:20.18.1
    ports:
      - 4001:3007
    volumes:
      - ./:/usr/src/eventify
    working_dir: /usr/src/eventify

    networks:
      - monorepo-network

    # FOR PRODUCTION
    command: bash -c "rm -rf dist && rm -rf node_modules && npm install && npm run build && npm run start:prod"
  batch:
    container_name: batch
    restart: unless-stopped
    image: node:20.18.1
    ports:
      - 4002:3008
    volumes:
      - ./:/usr/src/eventify
    working_dir: /usr/src/eventify

    networks:
      - monorepo-network

    # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod:batch"

networks:
  monorepo-network:
    driver: bridge
